import Foundation

/// The app-server wire omits JSON-RPC's `jsonrpc` member. This codec is deliberately
/// separate from circlr's MCP codec and has no knowledge of account credentials.
public enum CodexJSONValue: Codable, Equatable {
    case object([String: CodexJSONValue])
    case array([CodexJSONValue])
    case string(String)
    case integer(Int)
    case number(Double)
    case bool(Bool)
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() { self = .null }
        else if let value = try? container.decode(Bool.self) { self = .bool(value) }
        else if let value = try? container.decode(Int.self) { self = .integer(value) }
        else if let value = try? container.decode(Double.self) { self = .number(value) }
        else if let value = try? container.decode(String.self) { self = .string(value) }
        else if let value = try? container.decode([String: CodexJSONValue].self) { self = .object(value) }
        else { self = .array(try container.decode([CodexJSONValue].self)) }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .object(let value): try container.encode(value)
        case .array(let value): try container.encode(value)
        case .string(let value): try container.encode(value)
        case .integer(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }

    public subscript(_ key: String) -> CodexJSONValue? {
        guard case .object(let value) = self else { return nil }
        return value[key]
    }

    public var string: String? {
        guard case .string(let value) = self else { return nil }
        return value
    }

    public var object: [String: CodexJSONValue]? {
        guard case .object(let value) = self else { return nil }
        return value
    }
}

public enum CodexRPCID: Hashable, Equatable {
    case integer(Int)
    case string(String)

    var json: CodexJSONValue {
        switch self {
        case .integer(let value): return .integer(value)
        case .string(let value): return .string(value)
        }
    }

    init?(_ json: CodexJSONValue) {
        switch json {
        case .integer(let value): self = .integer(value)
        case .string(let value) where !value.isEmpty: self = .string(value)
        default: return nil
        }
    }
}

/// Client and server IDs occupy different Swift types even if their wire values match.
public struct CodexClientRequestID: Hashable, Equatable {
    public let value: CodexRPCID
    public init(_ value: Int) { self.value = .integer(value) }
    init(_ value: CodexRPCID) { self.value = value }
}

public struct CodexServerRequestID: Hashable, Equatable {
    public let value: CodexRPCID
    init(_ value: CodexRPCID) { self.value = value }
}

public struct CodexRPCError: Equatable {
    public let code: Int
    public let message: String

    init?(json: CodexJSONValue) {
        guard case .integer(let code)? = json["code"],
              let message = json["message"]?.string, !message.isEmpty else { return nil }
        self.code = code
        self.message = message
    }
}

public enum CodexWireMessage: Equatable {
    case response(id: CodexClientRequestID, result: CodexJSONValue?, error: CodexRPCError?)
    case serverRequest(id: CodexServerRequestID, method: String, params: CodexJSONValue)
    case notification(method: String, params: CodexJSONValue)
}

public enum CodexProtocolError: Error, Equatable {
    case malformedJSON
    case malformedEnvelope
    case unsupportedJSONRPCHeader
    case lineTooLong
    case tooManyMessages
    case outboundQueueFull
    case invalidState
    case unexpectedResponse
    case requiredField(String)
    case tooManyPendingServerRequests
    case tooManyPendingClientRequests
    case tooManyDeferredTurns
    case tooManyDeferredItems
    case accumulatedTextTooLong
    case staleGeneration
}

/// The account projection deliberately cannot carry an email address or token.
public enum CodexAccountAuthMode: Equatable {
    case signedOut
    case apiKey
    case chatGPT
    case amazonBedrock
}

/// Values generated by `codex app-server generate-ts` for CLI 0.149.1.
public enum CodexAccountPlan: String, Equatable {
    case free, go, plus, pro, prolite, team
    case selfServeBusinessProlite = "self_serve_business_prolite"
    case selfServeBusinessUsageBased = "self_serve_business_usage_based"
    case business, ent26
    case enterpriseCBPAutomation = "enterprise_cbp_automation"
    case enterpriseCBPUsageBased = "enterprise_cbp_usage_based"
    case enterprise, edu
    case eduPlus = "edu_plus"
    case eduPro = "edu_pro"
    case unknown
}

public struct CodexAccountSummary: Equatable {
    public let authMode: CodexAccountAuthMode
    public let plan: CodexAccountPlan?

    public init(authMode: CodexAccountAuthMode, plan: CodexAccountPlan?) {
        self.authMode = authMode
        self.plan = plan
    }

    init(json: CodexJSONValue) throws {
        guard case .bool = json["requiresOpenaiAuth"] else {
            throw CodexProtocolError.requiredField("account/read.requiresOpenaiAuth")
        }
        // The account member is optional in the runtime schema. Missing and
        // null both mean that this response confirms no signed-in account.
        switch json["account"] ?? .null {
        case .null:
            self.init(authMode: .signedOut, plan: nil)
        case .object(let account):
            switch account["type"]?.string {
            case "apiKey": self.init(authMode: .apiKey, plan: nil)
            case "chatgpt":
                let plan: CodexAccountPlan
                switch account["planType"] {
                case .string(let value)?: plan = CodexAccountPlan(rawValue: value) ?? .unknown
                case .null?: plan = .unknown
                default: throw CodexProtocolError.requiredField("account/read.account.planType")
                }
                self.init(authMode: .chatGPT, plan: plan)
            case "amazonBedrock": self.init(authMode: .amazonBedrock, plan: nil)
            default: throw CodexProtocolError.requiredField("account/read.account.type")
            }
        default:
            throw CodexProtocolError.requiredField("account/read.account")
        }
    }
}

/// A minimal projection of one entry from the current account's `model/list`.
public struct CodexModelSummary: Equatable {
    public let id: String
    public let isDefault: Bool

    public init(id: String, isDefault: Bool) {
        self.id = id
        self.isDefault = isDefault
    }

    init(json: CodexJSONValue) throws {
        guard let id = json["id"]?.string, !id.isEmpty,
              case .bool(let isDefault)? = json["isDefault"] else {
            throw CodexProtocolError.requiredField("model/list.data.id/isDefault")
        }
        self.id = id
        self.isDefault = isDefault
    }
}

public struct CodexModelPage: Equatable {
    public let models: [CodexModelSummary]
    public let nextCursor: String?

    public init(models: [CodexModelSummary], nextCursor: String?) {
        self.models = models
        self.nextCursor = nextCursor
    }

    init(json: CodexJSONValue) throws {
        guard case .array(let entries)? = json["data"] else {
            throw CodexProtocolError.requiredField("model/list.data")
        }
        let models = try entries.map(CodexModelSummary.init(json:))
        guard Set(models.map(\.id)).count == models.count else {
            throw CodexProtocolError.malformedEnvelope
        }
        switch json["nextCursor"] ?? .null {
        case .null: self.nextCursor = nil
        case .string(let value) where !value.isEmpty: self.nextCursor = value
        default: throw CodexProtocolError.requiredField("model/list.nextCursor")
        }
        self.models = models
    }
}

public enum CodexWire {
    public static func decode(_ line: Data) throws -> CodexWireMessage {
        let value: CodexJSONValue
        do { value = try JSONDecoder().decode(CodexJSONValue.self, from: line) }
        catch { throw CodexProtocolError.malformedJSON }
        guard let object = value.object else { throw CodexProtocolError.malformedEnvelope }
        if object["jsonrpc"] != nil { throw CodexProtocolError.unsupportedJSONRPCHeader }

        if let methodValue = object["method"] {
            guard let method = methodValue.string, !method.isEmpty,
                  case .object = object["params"] ?? .object([:]) else {
                throw CodexProtocolError.malformedEnvelope
            }
            let params = object["params"] ?? .object([:])
            if let idValue = object["id"] {
                guard let id = CodexRPCID(idValue),
                      object["result"] == nil, object["error"] == nil else {
                    throw CodexProtocolError.malformedEnvelope
                }
                return .serverRequest(id: CodexServerRequestID(id), method: method, params: params)
            }
            guard object["result"] == nil, object["error"] == nil else {
                throw CodexProtocolError.malformedEnvelope
            }
            return .notification(method: method, params: params)
        }

        guard let idValue = object["id"], let id = CodexRPCID(idValue) else {
            throw CodexProtocolError.malformedEnvelope
        }
        let hasResult = object["result"] != nil
        let hasError = object["error"] != nil
        guard hasResult != hasError else { throw CodexProtocolError.malformedEnvelope }
        if let errorValue = object["error"] {
            guard let error = CodexRPCError(json: errorValue) else {
                throw CodexProtocolError.malformedEnvelope
            }
            return .response(id: CodexClientRequestID(id), result: nil, error: error)
        }
        return .response(id: CodexClientRequestID(id), result: object["result"], error: nil)
    }

    public static func request(id: CodexClientRequestID, method: String, params: CodexJSONValue) throws -> Data {
        try encode(.object(["id": id.value.json, "method": .string(method), "params": params]))
    }

    public static func notification(method: String, params: CodexJSONValue = .object([:])) throws -> Data {
        try encode(.object(["method": .string(method), "params": params]))
    }

    public static func serverReply(id: CodexServerRequestID, result: CodexJSONValue) throws -> Data {
        try encode(.object(["id": id.value.json, "result": result]))
    }

    public static func serverErrorReply(id: CodexServerRequestID,
                                        code: Int, message: String) throws -> Data {
        try encode(.object(["id": id.value.json, "error": .object([
            "code": .integer(code), "message": .string(message)
        ])]))
    }

    private static func encode(_ value: CodexJSONValue) throws -> Data {
        var data = try JSONEncoder().encode(value)
        data.append(0x0A)
        return data
    }
}
